### ISSUE TITLE
player.markers.add doesn't work

### ISSUE THREAD

**Issue by MartijnGrul** [spchuang/videojs-markers#68]
I'm working on a project where i need to add markers from a json array. However adding markers dinamycly is not possible. This is my code:

    player.markers({
        markers: []
    });

    if(bookmarks_array.length !== 0){
        bookmarks_array.forEach(function(bookmark) {
            console.log(bookmark);

            var color_bookmark = "";

            if(bookmark.public == true){
                color_bookmark = "green";
            }else{
                color_bookmark = "blue";
            }

            player.markers.add({
                markers: [{
                    time: bookmark.postion,
                    text: bookmark.content,
                    class: color_bookmark
                }]
            });

        });
    }

The error i'm getting is:

> VIDEOJS: ERROR: TypeError: Cannot read property 'time' of undefined
    at Object.time (/js/video-js/videojs-markers/videojs.markers.js:17:22)
    at e.onTimeUpdate (/js/video-js/videojs-markers/videojs.markers.js:251:45)
    at HTMLDivElement.r (/js/video-js/video.min.js:2:378)
    at HTMLDivElement.U.r.dispatcher.r.dispatcher (/js/video-js/video.min.js:1:6923)
    at X (/js/video-js/video.min.js:1:7602)
    at e.trigger (/js/video-js/video.min.js:2:2969)
    at e.so.(anonymous function) [as handleTechTimeupdate_] (/js/video-js/video.min.js:6:17654)
    at e.r (/js/video-js/video.min.js:2:378)
    at HTMLVideoElement.r (/js/video-js/video.min.js:2:378)
    at HTMLVideoElement.U.r.dispatcher.r.dispatcher (/js/video-js/video.min.js:1:6923)

Sometimes i also get the error that the function "player.markers.add" does not exists. Any suggestions at what i'm doing wrong?

**Comment by ikovic** [comment]
You are sending an object with `markers` property as an array to `player.markers.add` function. You should just send the array containing the marker descriptors.

**Comment by spchuang** [comment]
As @ikovic  suggested, for the `add` function, you only need to pass in an array of marker objects. so something like

```
player.markers.add([{time: ..., text: ..., class: ...}]);
```
